--------------------------------------------------------
--  File created - Monday-April-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COUNTRIES" 
   (	"GDP_PER_CAPITA" NUMBER(10,0) DEFAULT NULL, 
	"COUNTRY_ID" NUMBER(10,0), 
	"COUNTRY_NAME" VARCHAR2(10 BYTE) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.COUNTRIES
SET DEFINE OFF;
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (95524,0,'pakistan');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (22546,1,'austrailia');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (66390,2,'japan');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (66745,3,'filpine');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (88788,4,'malasia');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (24052,5,'uae');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (29490,6,'usa');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (85318,7,'china');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (91356,8,'canada');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (37194,9,'saudia ');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (23642,10,'turkey');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (56821,11,'indonesia');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (97860,12,'uk');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (25684,13,'fiji');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (24281,14,'spain');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (73296,15,'austria');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (86741,16,'belgium');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (34403,17,'france');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (93476,18,'italy');
Insert into SYSTEM.COUNTRIES (GDP_PER_CAPITA,COUNTRY_ID,COUNTRY_NAME) values (67805,19,'brunei');
--------------------------------------------------------
--  DDL for Index SYS_C007357
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007357" ON "SYSTEM"."COUNTRIES" ("COUNTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COUNTRIES" ADD PRIMARY KEY ("COUNTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
