--------------------------------------------------------
--  File created - Monday-April-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USERS" 
   (	"AGE" NUMBER(10,0) DEFAULT NULL, 
	"GENDER" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"SALARY" NUMBER(10,0) DEFAULT NULL, 
	"ID" NUMBER(10,0), 
	"COUNTRY_ID" NUMBER(10,0) DEFAULT NULL, 
	"NAME" VARCHAR2(20 BYTE), 
	"MODEL_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USERS
SET DEFINE OFF;
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (72,'Female',73959,0,5,'ayesha',1);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (76,'Female',23186,1,0,'fatima',2);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (66,'Male',46737,2,7,'usama',4);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (55,'Female',46244,3,9,'bushra',7);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (50,'Male',67377,4,13,'shahid',3);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (40,'Male',79199,5,6,'mudassir',2);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (69,'Male',37962,6,4,'habib',1);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (71,'Male',65128,7,2,'shakeel',7);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (45,'Male',38190,8,7,'mustafa',9);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (23,'Female',58053,9,7,'mehak',4);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (59,'Female',57439,10,17,'manahil',2);
Insert into SYSTEM.USERS (AGE,GENDER,SALARY,ID,COUNTRY_ID,NAME,MODEL_ID) values (23,'Male',75481,11,5,'mubashir',6);
--------------------------------------------------------
--  DDL for Index SYS_C007359
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007359" ON "SYSTEM"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USERS" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "USERS_FK1" FOREIGN KEY ("MODEL_ID")
	  REFERENCES "SYSTEM"."MODELS" ("MODEL_ID") ENABLE;
  ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "USERS_IBFK_1" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "SYSTEM"."COUNTRIES" ("COUNTRY_ID") ENABLE;
